package engine

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/chaz8081/positive-vibes/pkg/schema"
)

type SkillGenerator interface {
	Generate(description string) (*schema.Skill, error)
}

type MockGenerator struct{}

func NewMockGenerator() *MockGenerator { return &MockGenerator{} }

func (m *MockGenerator) Generate(description string) (*schema.Skill, error) {
	name := slugify(description)
	sk := &schema.Skill{
		Name:         name,
		Description:  description,
		Version:      "1.0",
		Author:       "positive-vibes-generate",
		Tags:         []string{"generated"},
		Instructions: fmt.Sprintf("# %s\n\n%s\n\nThis skill was auto-generated by positive-vibes.\nCustomize it to fit your needs!", description, description),
	}
	return sk, nil
}

func slugify(s string) string {
	s = strings.ToLower(s)
	// replace non alnum with hyphens
	re := regexp.MustCompile(`[^a-z0-9]+`)
	out := re.ReplaceAllString(s, "-")
	out = strings.Trim(out, "-")
	return out
}
